[package]
name = "ch03_the_twelve_days_of_christmas"
version = "0.1.0"
authors = ["Gunther Schulz <dev@guntherschulzu.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
